### ISSUE TITLE
Discourse-Button disappearing

### ISSUE THREAD

**Issue by Misanth420** [MetaFam/metagame-wiki#190] opened 2021-01-13 07:28 UTC
Wasn't sure whether to post the issue here or under MetaGame Website-please correct me
-When viewing the discourse forum, if you enter a thread and scroll down, the "wiki" button disappears.
-It seems to disappear only when you enter a thread and scroll down, regardless of location.
-Is this intended to work like that?
![Discourse_screenshot](https://user-images.githubusercontent.com/77243213/104416446-1ada1800-5574-11eb-90cd-4fa82b4ac748.png)

**Comment by SLRead** [comment] 2021-01-16 21:59
Confirmed this behaviour.  It happens when the title bar switches from the MetaGame logo to the thread title.  So it is likely just missing from the menu location that holds the thread title.

**Comment by luxumbra** [comment] 2021-06-06 22:01
Bizarre. I'd say this was an issue with the Discourse UI rather than a wiki issue. I am not sure how much control we have over that.

**Comment by Baconaetor** [comment] 2021-08-10 03:16
I suspect this is because the thread title is longer, so it's compressing the button options on the right. Must be a max of four while the title is shown, so it drops the middle one as it compresses. As @luxumbra said, I doubt there is much we can do about this as it's probably on the Discourse side. Also, as My Meta is built out and starts to include the wiki it should be a null issue. I'll close this issue now for those reasons, and because it's not really a wiki issue. Although I'd greatly appreciate it if one of our Discourse admins can check and verify if this is a Discourse or us issue.

**Closed by Baconaetor** 2021-08-10 03:16 UTC
